#!/usr/bin/env bun
/**
 * Automation-event emitter gate.
 *
 * `AGENT_EVENTS` is the vocabulary the automations UI and schema accept, but a
 * member nobody emits is a configuration surface that can never fire: the user
 * writes an automation, the config validates, and nothing ever happens. Eight of
 * the thirteen members were in exactly that state.
 *
 * This gate scans the real emission sites and compares them with
 * `UNEMITTED_AGENT_EVENTS`, the list the product uses to warn users. The two must
 * agree, which closes the loop in both directions: adding an emitter forces the
 * warning list to shrink, and adding a vocabulary member with no emitter fails
 * immediately rather than shipping another silent no-op.
 *
 * Usage:
 *   bun run scripts/check-automation-events.ts
 *   bun run scripts/check-automation-events.ts --update
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'

const root = resolve(process.argv.find(arg => arg.startsWith('--repository='))?.slice(13) ?? resolve(import.meta.dir, '..'))
const update = process.argv.includes('--update')
const pathName = (file: string) => relative(root, file).replaceAll('\\', '/')

const TYPES = join(root, 'packages/shared/src/automations/types.ts')
const CONSTANT_FILE = join(root, 'packages/shared/src/automations/emitted-events.ts')
const BASELINE = join(import.meta.dir, 'automation-events-baseline.json')

/** Read a `const NAME[: Type[]] = [...]` string-literal list out of a source file. */
function readVocabulary(source: string, name: string): string[] {
  const match = source.match(new RegExp(`export const ${name}\\s*(?::[^=]*)?=\\s*\\[([\\s\\S]*?)\\]`))
  if (!match) throw new Error(`vocabulary not found: ${name}`)
  return [...match[1]!.matchAll(/'([^']+)'/g)].map(m => m[1]!)
}

function walk(directory: string, files: string[] = []): string[] {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) { if (!['node_modules', 'dist', '__tests__', 'fixtures'].includes(entry.name)) walk(path, files) }
    else if (/\.tsx?$/.test(entry.name) && !/\.(test|isolated)\.[jt]sx?$/.test(entry.name)) files.push(path)
  }
  return files
}

const typesSource = readFileSync(TYPES, 'utf8')
const agentEvents = readVocabulary(typesSource, 'AGENT_EVENTS')
const known = new Set(agentEvents)

/**
 * Every event an `emitAutomationEvent(...)` call can carry. The first argument is
 * either a literal or a local variable holding one (pi-agent derives its tool
 * event name from `agentEvent.isError`), so an identifier is resolved against the
 * string literals assigned to it in the same file.
 */
function findEmitted(events: Set<string>): Map<string, string[]> {
  const emitted = new Map<string, string[]>()
  const record = (event: string, file: string) => {
    if (!events.has(event)) return
    if (!emitted.has(event)) emitted.set(event, [])
    emitted.get(event)!.push(file)
  }
  for (const directory of ['packages', 'apps']) {
    for (const file of walk(join(root, directory))) {
      const source = readFileSync(file, 'utf8')
      if (!source.includes('emitAutomationEvent(')) continue
      for (const call of source.matchAll(/emitAutomationEvent\(\s*([^,)]+)/g)) {
        const argument = call[1]!.trim()
        const literal = argument.match(/^'([^']+)'$/)
        if (literal) { record(literal[1]!, pathName(file)); continue }
        for (const identifier of argument.matchAll(/[A-Za-z_$][\w$]*/g)) {
          const assigned = source.match(new RegExp(`(?:const|let|var)\\s+${identifier[0]}\\s*=\\s*([^;\\n]+)`))
          if (!assigned) continue
          for (const value of assigned[1]!.matchAll(/'([^']+)'/g)) record(value[1]!, pathName(file))
        }
      }
    }
  }
  return emitted
}

const emitted = findEmitted(known)
const unemitted = agentEvents.filter(event => !emitted.has(event)).sort()
const wired = agentEvents.filter(event => emitted.has(event)).sort()

if (update) {
  writeFileSync(CONSTANT_FILE, `/**
 * Agent events nobody emits yet.
 *
 * GENERATED by \`bun run scripts/check-automation-events.ts --update\`; do not hand-edit.
 * Every member here is accepted by the automations schema but can never fire, so the
 * product warns the user instead of silently accepting the config. Adding an emitter
 * removes an entry; adding a vocabulary member without an emitter adds one and is a
 * decision, not an oversight.
 */
export const UNEMITTED_AGENT_EVENTS = [
${unemitted.map(event => `  '${event}',`).join('\n')}
] as const;

/** Agent events with at least one emission site. */
export const EMITTED_AGENT_EVENTS = [
${wired.map(event => `  '${event}',`).join('\n')}
] as const;
`)
  writeFileSync(BASELINE, JSON.stringify({
    $comment: 'Agent events with no emission site. Implement the hook or remove the vocabulary member; never grow this to make a build pass.',
    generatedAt: new Date().toISOString(),
    allowed: unemitted,
  }, null, 2) + '\n')
  console.log(`wrote ${pathName(CONSTANT_FILE)} and the baseline: ${wired.length} emitted, ${unemitted.length} unemitted`)
}

const failures: string[] = []
if (!readFileSync(CONSTANT_FILE, 'utf8').includes(`'${unemitted[0]}'`) && unemitted.length > 0) {
  failures.push(`${pathName(CONSTANT_FILE)} is out of date; run --update`)
}
const declared = readVocabulary(readFileSync(CONSTANT_FILE, 'utf8'), 'UNEMITTED_AGENT_EVENTS').sort()
for (const event of unemitted) if (!declared.includes(event)) failures.push(`UNEMITTED_AGENT_EVENTS is missing '${event}' (no emitter found); run --update`)
for (const event of declared) if (!unemitted.includes(event)) failures.push(`UNEMITTED_AGENT_EVENTS still lists '${event}', but some code now emits it; remove the warning entry`)

const baseline = JSON.parse(readFileSync(BASELINE, 'utf8')) as { allowed?: string[]; $comment?: string }
const allowed = baseline.allowed ?? []
for (const event of unemitted) if (!allowed.includes(event)) failures.push(`'${event}' has no emitter and is not in the recorded baseline; implement the hook, remove the vocabulary member, or record the decision with --update`)
if (unemitted.length !== allowed.length) failures.push(`baseline has ${allowed.length} entries but ${unemitted.length} events are unemitted; run --update`)

const result = {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  vocabularySize: agentEvents.length,
  emittedCount: wired.length,
  unemittedCount: unemitted.length,
  emitted,
  unemitted,
  failures,
}
console.log(JSON.stringify(result, null, 2))
if (failures.length) process.exitCode = 1
