/**
 * Agent events nobody emits yet.
 *
 * GENERATED by `bun run scripts/check-automation-events.ts --update`; do not hand-edit.
 * Every member here is accepted by the automations schema but can never fire, so the
 * product warns the user instead of silently accepting the config. Adding an emitter
 * removes an entry; adding a vocabulary member without an emitter adds one and is a
 * decision, not an oversight.
 */
export const UNEMITTED_AGENT_EVENTS = [
  'Notification',
  'PermissionRequest',
  'PreCompact',
  'SessionEnd',
  'SessionStart',
  'Setup',
  'SubagentStart',
  'SubagentStop',
] as const;

/** Agent events with at least one emission site. */
export const EMITTED_AGENT_EVENTS = [
  'PostToolUse',
  'PostToolUseFailure',
  'PreToolUse',
  'Stop',
  'UserPromptSubmit',
] as const;
