/** Acceptance workflows written before the AI settings structure implementation. */
import { strict as assert } from 'node:assert'
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createServer } from 'vite'
import { chromium } from 'playwright'
const root = resolve(import.meta.dir, '../..'), output = resolve(root, '.cache/ai-settings-structure')
mkdirSync(output, { recursive: true })
writeFileSync(resolve(output, 'settings.html'), '<!doctype html><html><head><meta charset="utf-8"></head><body><div id="root"></div><script type="module" src="/scripts/verification/fixtures/ai-settings-structure.tsx"></script></body></html>')
const server = await createServer({ configFile: resolve(root, 'apps/electron/vite.config.ts'), root, server: { host: '127.0.0.1', port: 0, open: false, watch: { ignored: ['**/runtimes/**'] } } })
await server.listen()
const address = server.httpServer!.address() as { port: number }, base = `http://127.0.0.1:${address.port}/.cache/ai-settings-structure/settings.html`
const browser = await chromium.launch({ headless: true, channel: process.env.PHANERIS_TEST_BROWSER_CHANNEL })
const page = await browser.newPage({ viewport: { width: 1040, height: 1000 } })
page.setDefaultTimeout(5000)
const records: Array<{ id: string; pass: boolean; error?: string }> = [], errors: string[] = []
const options = page.locator('[data-slot="popover-content"][data-state="open"] [data-option]')
const advanced = (id: string) => page.locator(`[data-ai-advanced="${id}"]`)
const toggle = (id: string) => advanced(id).locator('[data-ai-advanced-toggle]')
page.on('pageerror', error => errors.push(error.message))
async function check(id: string, action: () => Promise<void>) {
  try { await action(); records.push({ id, pass: true }) } catch (error) { records.push({ id, pass: false, error: error instanceof Error ? error.stack : String(error) }); await page.screenshot({ path: resolve(output, `failure-${records.length}.png`) }).catch(() => {}) }
  console.log(`${records.at(-1)!.pass ? 'PASS' : 'FAIL'} ${id}`)
}
async function load(query = '') {
  await page.goto(`${base}?${query}`, { waitUntil: 'networkidle', timeout: 90000 })
  await page.waitForFunction(() => typeof (window as any).aiStructureState === 'function')
  await page.locator('[data-ai-settings-section="connections"], [data-workspace-conversation-settings]').first().waitFor()
}
async function choose(control: ReturnType<typeof page.locator>, label: string) { await control.click(); await options.filter({ hasText: new RegExp('^' + label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) }).click() }
try {
  await check('Connections, conversation, advanced; no tabs and independent collapsed summaries', async () => {
    await load()
    assert.deepEqual(await page.locator('[data-ai-settings-section]').evaluateAll(nodes => nodes.map(n => n.getAttribute('data-ai-settings-section'))), ['connections', 'conversation', 'advanced'])
    assert.equal(await page.getByRole('tablist').count(), 0)
    for (const id of ['images', 'decisions', 'performance']) { assert.equal(await toggle(id).getAttribute('aria-expanded'), 'false'); assert((await toggle(id).innerText()).trim().length > 15); await toggle(id).click() }
    for (const id of ['images', 'decisions', 'performance']) assert.equal(await toggle(id).getAttribute('aria-expanded'), 'true')
    assert.equal(await advanced('decisions').getByRole('button', { name: /Configuration|Configure/i }).count(), 0)
    await toggle('images').focus(); await page.keyboard.press('Enter')
    assert.equal(await toggle('images').getAttribute('aria-expanded'), 'false')
    assert.equal(await toggle('decisions').getAttribute('aria-expanded'), 'true'); assert.equal(await toggle('performance').getAttribute('aria-expanded'), 'true')
  })
  await check('Context is in conversation, on the right, with persistence and rollback', async () => {
    await load()
    const control = page.locator('#context-policy-select')
    assert.equal(await page.locator('[data-ai-settings-section="conversation"] #context-policy-select').count(), 1)
    assert(await control.evaluate(e => e.getBoundingClientRect().x >= e.closest('[data-layout="settings-row"]')!.querySelector('label')!.getBoundingClientRect().right))
    for (const label of ['Auto handoff', 'Manual', 'Auto compact']) await choose(control, label)
    await control.click(); await options.first().focus(); await page.keyboard.press('End'); await page.keyboard.press('Enter')
    await page.waitForFunction(() => (window as any).aiStructureState().contextPolicy === 'manual')
    await choose(control, 'Auto compact')
    await page.evaluate(() => { (window as any).aiStructureState().failContext = true })
    await choose(control, 'Manual'); await page.waitForFunction(() => document.getElementById('context-policy-select')?.textContent?.includes('Auto compact'))
    assert.equal(await page.evaluate(() => (window as any).aiStructureState().contextPolicy), 'compact')
  })
  await check('Workspace editor is owned by Workspace; switching connection clears a foreign model in one write', async () => {
    await load(); assert.equal(await page.getByRole('button', { name: /Writing|Design/ }).count(), 0)
    assert.equal(await page.locator('[data-workspace-conversation-settings]').count(), 0)
    await page.locator('[data-workspace-conversation-link]').click()
    const editor = page.locator('[data-workspace-conversation-settings]'); await editor.waitFor()
    await editor.getByLabel('Connection', { exact: true }).waitFor(); assert((await editor.innerText()).includes('OpenRouter'))
    await choose(editor.getByLabel('Connection', { exact: true }), 'OpenAI')
    await page.waitForFunction(() => !(window as any).aiStructureState().workspaceById['workspace-0'].model)
    const writes = await page.evaluate(() => (window as any).aiStructureState().calls.filter((c: any) => c.method === 'updateWorkspaceSetting'))
    assert.equal(writes.length, 1); assert.equal(writes[0].args[1], 'defaultLlmConnection')
    assert((await editor.locator('[data-workspace-effective]').innerText()).includes('5.4'))
  })
  await check('Global changes preserve workspace override; per-field inheritance uses the new global value', async () => {
    await load(); await choose(page.locator('#default-connection-select'), 'OpenRouter')
    assert.equal(await page.evaluate(() => (window as any).aiStructureState().workspaceById['workspace-0'].defaultLlmConnection), 'router')
    await page.locator('[data-workspace-conversation-link]').click()
    const editor = page.locator('[data-workspace-conversation-settings]'); await editor.waitFor()
    await choose(editor.getByLabel('Connection', { exact: true }), 'Use global default')
    await choose(editor.getByLabel('Model', { exact: true }), 'Connection default')
    assert((await editor.locator('[data-workspace-effective]').innerText()).includes('OpenRouter'))
    assert.equal(await page.evaluate(() => (window as any).aiStructureState().workspaceById['workspace-0'].defaultLlmConnection), undefined)
  })
  await check('Workspace save failure restores the choice; workspace switches isolate late loads', async () => {
    await load('page=workspace')
    const editor = page.locator('[data-workspace-conversation-settings]')
    await page.evaluate(() => { (window as any).aiStructureState().failWorkspace = true })
    await choose(editor.getByLabel('Connection', { exact: true }), 'OpenAI')
    await page.waitForFunction(() => document.querySelector('[data-workspace-conversation-settings]')?.textContent?.includes('OpenRouter'))
    assert.equal(await page.evaluate(() => (window as any).aiStructureState().workspaceById['workspace-0'].defaultLlmConnection), 'router')
    await page.evaluate(() => { const s = (window as any).aiStructureState(); s.delayWorkspace = true; s.failWorkspace = false; s.activeWorkspaceId = 'workspace-1'; (window as any).aiStructureRefresh() })
    await editor.getByLabel('Connection', { exact: true }).waitFor(); assert((await editor.innerText()).includes('Use global default'))
    await page.evaluate(() => { (window as any).aiStructureState().activeWorkspaceId = 'workspace-0'; (window as any).aiStructureRefresh() })
    await page.waitForTimeout(100)
    await page.evaluate(() => { (window as any).aiStructureState().activeWorkspaceId = 'workspace-1'; (window as any).aiStructureRefresh() })
    await page.waitForTimeout(800)
    assert((await editor.innerText()).includes('Use global default')); assert(!(await editor.locator('[data-workspace-effective]').innerText()).includes('OpenRouter'))
  })
  await check('Subscription-only images show neutral guidance and a compatible API-only setup', async () => {
    await load('scenario=subscription'); assert((await toggle('images').innerText()).includes('Not configured'))
    await toggle('images').click()
    assert.equal(await advanced('images').getByLabel('Connection', { exact: true }).count(), 0)
    assert((await advanced('images').innerText()).includes('ChatGPT'))
    assert.equal(await advanced('images').getByRole('alert').count(), 0, 'An optional unconfigured feature is a neutral state')
    await advanced('images').getByRole('button', { name: 'Add image generation connection' }).click()
    await page.locator('[data-testid="api-key-input"]').waitFor()
    await page.locator('[data-testid="api-key-preset-trigger"]').click()
    const menu = page.getByRole('menu')
    assert((await menu.innerText()).includes('OpenAI')); assert((await menu.innerText()).includes('OpenRouter'))
    assert(!(await menu.innerText()).includes('Anthropic')); assert(!(await menu.innerText()).includes('Minimax')); assert(!(await menu.innerText()).includes('ChatGPT'))
    assert.equal(await page.evaluate(() => (window as any).aiStructureState().calls.filter((c: any) => c.method === 'saveLlmConnection').length), 0)
    await page.keyboard.press('Escape'); await page.locator('[data-onboarding-close]').click()
    await page.getByRole('button', { name: '+ Add Connection', exact: true }).click()
    await page.getByText('Codex · ChatGPT Plus', { exact: true }).waitFor()
  })
  await check('Compatible image setup saves only on submission and preserves the default conversation', async () => {
    await load('scenario=subscription'); await toggle('images').click()
    await advanced('images').getByRole('button', { name: 'Add image generation connection' }).click()
    await page.locator('#api-key').fill('synthetic-fixture-key')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByRole('button', { name: 'Get Started', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('[data-ai-advanced="images"]')?.textContent?.includes('Image API'))
    const state = await page.evaluate(() => (window as any).aiStructureState())
    const setup = state.calls.find((call: any) => call.method === 'setupLlmConnection')
    assert.equal(setup.args[0].piAuthProvider, 'openai'); assert.equal(state.connections.find((c: any) => c.isDefault).slug, 'chatgpt')
    assert.deepEqual(state.image, {})
  })
  await check('Workspace load failure exposes retry and does not invent editable defaults', async () => {
    await load('scenario=workspace-error&page=workspace')
    const editor = page.locator('[data-workspace-conversation-settings]')
    await editor.getByRole('button', { name: 'Retry' }).waitFor()
    assert.equal(await editor.getByLabel('Connection', { exact: true }).count(), 0)
    await page.evaluate(() => { (window as any).aiStructureState().failWorkspaceLoad = false })
    await editor.getByRole('button', { name: 'Retry' }).click()
    await editor.getByLabel('Connection', { exact: true }).waitFor()
  })
  await check('Image automatic account is explicit; switching accounts resets model; save failure keeps prior choice', async () => {
    await load(); assert((await toggle('images').innerText()).includes('Automatic: OpenAI'))
    await toggle('images').click(); const image = advanced('images')
    await choose(image.getByLabel('Connection', { exact: true }), 'OpenAI')
    await choose(image.getByLabel('Model', { exact: true }), 'GPT Image 2')
    await choose(image.getByLabel('Connection', { exact: true }), 'OpenRouter')
    assert.deepEqual(await page.evaluate(() => (window as any).aiStructureState().image), { connectionSlug: 'router' })
    await page.evaluate(() => { (window as any).aiStructureState().failImages = true })
    await choose(image.getByLabel('Connection', { exact: true }), 'OpenAI')
    assert.equal(await page.evaluate(() => (window as any).aiStructureState().image.connectionSlug), 'router')
    assert((await image.innerText()).includes('Fixture image save failed'))
  })
  for (const scenario of ['broken', 'deleted']) await check(`${scenario} explicit image account is preserved without fallback`, async () => {
    await load(`scenario=${scenario}`); await toggle('images').click()
    assert((await advanced('images').innerText()).includes('selected image account is unavailable'))
    const s = await page.evaluate(() => (window as any).aiStructureState())
    assert.equal(s.image.connectionSlug, scenario === 'broken' ? 'openai' : 'deleted-account')
    assert((await advanced('images').getByLabel('Connection', { exact: true }).innerText()).includes(scenario === 'broken' ? 'OpenAI' : 'deleted-account'))
  })
  await check('Image request failure is visible and can retry instead of claiming unconfigured', async () => {
    await load('scenario=image-error'); await toggle('images').click()
    assert((await advanced('images').innerText()).includes('Fixture image status unavailable'))
    await page.evaluate(() => { (window as any).aiStructureState().failImageLoad = false })
    await advanced('images').getByRole('button', { name: 'Retry' }).click()
    await page.waitForFunction(() => document.querySelector('[data-ai-advanced="images"]')?.textContent?.includes('Automatic: OpenAI'))
  })
  await check('Decisions are configurable while disabled; features are in the same disclosure', async () => {
    await load(); await toggle('decisions').click()
    assert.equal(await advanced('decisions').getByLabel('Provider / key source', { exact: true }).count(), 1)
    assert.equal(await advanced('decisions').getByRole('switch').count(), 4)
    assert((await advanced('decisions').innerText()).includes('Guarded'))
    assert.equal(await page.locator('[data-ai-settings-section]').count(), 3)
  })
  await check('Guarded Permissions entry opens only decision assistance', async () => {
    await load(); await page.evaluate(() => (window as any).aiStructureNavigate('permissions'))
    await page.getByRole('button', { name: 'Configure decision model' }).click()
    await toggle('decisions').waitFor(); assert.equal(await toggle('decisions').getAttribute('aria-expanded'), 'true')
    assert.equal(await toggle('images').getAttribute('aria-expanded'), 'false'); assert.equal(await toggle('performance').getAttribute('aria-expanded'), 'false')
  })
  await check('Decision load failure leaves a visible section with retry', async () => {
    await load('scenario=decision-error'); await toggle('decisions').click()
    assert((await advanced('decisions').innerText()).includes('Fixture decision unavailable'))
    await page.evaluate(() => { (window as any).aiStructureState().failDecisions = false })
    await advanced('decisions').getByRole('button', { name: 'Retry' }).click()
    await advanced('decisions').getByLabel('Provider / key source', { exact: true }).waitFor()
  })
  await check('Connection identity, capability scope, default purpose and persistent validation', async () => {
    await load(); const connections = page.locator('[data-ai-settings-section="connections"]')
    assert(!(await connections.innerText()).includes('Phaneris Backend'))
    const subscription = connections.locator('[data-connection-slug="chatgpt"]')
    assert((await subscription.innerText()).includes('Subscription sign-in')); assert((await subscription.innerText()).includes('Some models support image understanding'))
    assert((await connections.innerText()).includes('Default conversations'))
    const row = connections.locator('[data-connection-slug="openai"]'); await row.getByRole('button').click()
    await page.getByRole('menuitem', { name: 'Validate Connection' }).click()
    await page.getByText(/Fixture authentication failed/).waitFor(); await page.waitForTimeout(250)
    await row.getByRole('button').click(); await page.getByRole('menuitem', { name: 'Rename', exact: true }).click(); await page.getByRole('dialog').waitFor(); await page.keyboard.press('Escape')
  })
  await check('Cache and runtime controls persist across disclosure and rollback failed changes', async () => {
    await load(); await toggle('performance').click()
    const cache = advanced('performance').getByRole('switch').first(), rtk = advanced('performance').getByRole('switch').last()
    await cache.click(); assert.equal(await cache.getAttribute('aria-checked'), 'true')
    await toggle('performance').click(); await toggle('performance').click(); assert.equal(await cache.getAttribute('aria-checked'), 'true')
    await page.evaluate(() => { (window as any).aiStructureState().failCache = true })
    await cache.click(); await page.waitForTimeout(180); assert.equal(await cache.getAttribute('aria-checked'), 'true')
    await rtk.click(); await page.waitForTimeout(180); assert.equal(await rtk.getAttribute('aria-checked'), 'false')
    assert((await advanced('performance').innerText()).includes('Token Optimization'))
  })
  for (const variant of [{ mode: 'light', lang: 'en', width: 1040 }, { mode: 'dark', lang: 'en', width: 1040 }, { mode: 'light', lang: 'zh-Hans', width: 480 }]) await check(`${variant.mode} ${variant.lang} ${variant.width}px visual artifact and layout`, async () => {
    await page.setViewportSize({ width: variant.width, height: 1000 }); await load(`mode=${variant.mode}&lang=${variant.lang}`)
    await page.screenshot({ path: resolve(output, `${variant.mode}-${variant.lang}-${variant.width}-top.png`) })
    await toggle('images').click(); await advanced('images').scrollIntoViewIfNeeded()
    await page.screenshot({ path: resolve(output, `${variant.mode}-${variant.lang}-${variant.width}-images.png`) })
    await toggle('decisions').click(); await advanced('decisions').scrollIntoViewIfNeeded()
    await page.screenshot({ path: resolve(output, `${variant.mode}-${variant.lang}-${variant.width}-decisions.png`) })
    await toggle('performance').click(); await advanced('performance').scrollIntoViewIfNeeded()
    await page.screenshot({ path: resolve(output, `${variant.mode}-${variant.lang}-${variant.width}-performance.png`) })
    await page.locator('[data-workspace-conversation-link]').click(); await page.locator('[data-workspace-conversation-settings]').scrollIntoViewIfNeeded()
    await page.screenshot({ path: resolve(output, `${variant.mode}-${variant.lang}-${variant.width}-workspace.png`) })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Horizontal overflow')
    assert(!/settings\.(ai|workspace)\.|permissions\.guarded/.test(await page.locator('#root').innerText()), 'Untranslated keys')
  })
} finally {
  await browser.close(); await server.close()
  writeFileSync(resolve(output, 'results.json'), JSON.stringify({ records, errors }, null, 2))
}
console.log(JSON.stringify({ records, errors })); process.exit(records.every(r => r.pass) && !errors.length ? 0 : 1)
